import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test'
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

// Regression guard for the quota crypto bug:
//   "internal: crypto: Unsupported state or unable to authenticate data"
//
// Root cause was loadOrCreateMasterKey() SILENTLY regenerating master.key.enc
// whenever it couldn't decode the existing file (on macOS, safeStorage's
// Keychain ACL is bound to the dev binary's code signature, which electron-
// rebuild re-signs before every launch — so the previously-written key failed
// to decrypt and a fresh key was generated, orphaning every stored credential).
//
// This test launches TWICE against the SAME user-data dir. Launch 1 imports a
// codex account (encrypts the credential under the master key). Launch 2 — a
// fresh process that re-loads the key from disk — exports it WITH credentials,
// which decrypts the envelope. If the key were regenerated between launches the
// decrypt would throw the exact auth-tag error; we assert it round-trips.

const TOKEN = 'codex-access-token-abc123.def456.ghi789'
const REFRESH = 'codex-refresh-token-zzz'

let app: ElectronApplication
let userDataDir: string

async function launch(): Promise<ElectronApplication> {
  return electron.launch({
    args: ['out/main/main.cjs'],
    env: { ...process.env, HXG_USER_DATA_DIR: userDataDir },
  })
}

test.beforeAll(() => {
  // ONE dir shared across both launches (simulates a real relaunch).
  userDataDir = mkdtempSync(join(tmpdir(), 'hxg-crypto-'))
})

test.afterEach(async () => {
  if (app) await app.close()
})

test.afterAll(() => {
  if (userDataDir) rmSync(userDataDir, { recursive: true, force: true })
})

test('credential stored on launch 1 decrypts on launch 2 (key is stable)', async () => {
  // ---- Launch 1: import (encrypt) ----
  app = await launch()
  let window = await app.firstWindow()
  await window.waitForLoadState('domcontentloaded')

  const imported = await window.evaluate(
    async ([token, refresh]) => {
      const api = (window as unknown as {
        api: { account: { importAccount(r: unknown): Promise<{ id: string }> } }
      }).api
      return api.account.importAccount({
        platform: 'codex',
        email: 'crypto-test@example.com',
        token,
        refreshToken: refresh,
        tags: [],
      })
    },
    [TOKEN, REFRESH],
  )
  expect(imported.id).toMatch(/^[0-9a-f-]{36}$/)
  const accountId = imported.id

  // The key file must exist after the first store.
  expect(existsSync(join(userDataDir, 'master.key.enc'))).toBe(true)
  const keyBytesAfterLaunch1 = readFileSync(join(userDataDir, 'master.key.enc'))

  await app.close()

  // ---- Launch 2: fresh process re-loads the key, export (decrypt) ----
  app = await launch()
  window = await app.firstWindow()
  await window.waitForLoadState('domcontentloaded')

  // The key file must NOT have been regenerated by the second launch.
  const keyBytesAfterLaunch2 = readFileSync(join(userDataDir, 'master.key.enc'))
  expect(keyBytesAfterLaunch2.equals(keyBytesAfterLaunch1)).toBe(true)

  // exportAccounts(includeCredentials:true) decrypts the stored envelope. This
  // is the operation that threw the auth-tag error before the fix.
  const exportJson = await window.evaluate(async (id) => {
    const api = (window as unknown as {
      api: { account: { exportAccounts(r: unknown): Promise<string> } }
    }).api
    return api.account.exportAccounts({ accountIds: [id], includeCredentials: true })
  }, accountId)

  const parsed = JSON.parse(exportJson) as {
    accounts: Array<{ id: string; credential?: { token: string; refresh_token: string | null } }>
  }
  const exported = parsed.accounts.find((a) => a.id === accountId)
  expect(exported).toBeDefined()
  expect(exported?.credential?.token).toBe(TOKEN)
  expect(exported?.credential?.refresh_token).toBe(REFRESH)
})
